### ISSUE TITLE
Need to fix llvm-project/llvm/test/Transforms/LoopVectorize/VE/disable_lv.ll

### ISSUE THREAD

**Issue by jam7** [sx-aurora-dev/llvm-project#44] opened 2021-07-06 06:44 UTC
@simoll -san, is it possible to check `feature/merge-upstream-20210401` branch?

The test, llvm-project/llvm/test/Transforms/LoopVectorize/VE/disable_lv.ll, fails on that branch.  The `opt` cannot optimized and vectorize a given program.

**Comment by jam7** [comment] 2021-07-06 08:16
In addition, the libcxxabi in this branch is not compilable because of 1687f2b modification.  So, please not try to compile libcxxabi.  :-)

**Comment by simoll** [comment] 2021-07-06 09:37
Fixed by https://github.com/sx-aurora-dev/llvm-project/commit/63cef7f11a4f3af14146fd2ce62b9cc679fd8d18
Vector register were not reported anymore (caused by tti change for scalable vreg support).

**Comment by kaz7** [comment] 2021-07-06 22:39
Merged this modification.  Thanks!

**Closed by kaz7** 2021-07-06 22:39 UTC
